#!/usr/bin/env sh
# This file is part of banias. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/banias/master/COPYRIGHT. No part of banias, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2015 The developers of banias. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/banias/master/COPYRIGHT.

_program()
{
	core_usesIn banias dependencies validate reports
    banias()
    {
		banias_dependencies_populateUname
		banias_dependencies_checkForPresenceOfLatex
		
		banias_validate_populatePotentialReportsIfNonOptionsEmpty
		banias_reports_makeReportsPathAbsolute
		banias_validate_populateReportsCheckingTheyAreValid
		
		banias_reports_createOutputPathAndMakeItAbsolute
		banias_reports_createTemporaryFileToConcatenateMarkdownTo
		banias_reports_registerConfiguration
        banias_reports_create
    }
}

_program_name='banias'
_program_version='unversioned'
_program_package_or_build=''
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/lib"
_program_etcPath="${_program_path}/etc"
_program_varPath="${_program_path}/var"
_program_entrypoint='banias'

_program_commandLine_parseInitialise()
{
	banias_reportsPath_default="$(pwd)"
	banias_outputPath_default="$banias_reportsPath_default"
	banias_format_default='pdf'
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_usage="[OPTION]... -- [REPORTs]...
"
	_program_commandLine_helpMessage_description="Creates PDF REPORTs from markdown fragments stored in Git; reports are folders"
	_program_commandLine_helpMessage_options="
  -r, --reports-path PATH  PATH to reports folder.
                           Defaults to '$banias_reportsPath_default'.
  -o, --output-path PATH   PATH to folder of output.
                           Defaults to '$banias_outputPath_default'.
  -f, --format FORMAT      FORMAT (one of pdf or latex)
                           Defaults to '$banias_format_default'.
If REPORTs are unspecified, all reports are used"
    _program_commandLine_helpMessage_optionsSpacing='   '
	_program_commandLine_helpMessage_configurationKeys="
  banias_reportsPath  Equivalent to --reports-path
  banias_outputPath   Equivalent to --output-path
  banias_format       Equivalent to --format
"
	_program_commandLine_helpMessage_examples="
  ${_program_name} my-report
"
}

_program_commandLine_optionExists()
{
	case "$optionName" in
		
		o|output-path)
			echo 'yes-argumented'
		;;
		
		r|reports-path)
			echo 'yes-argumented'
		;;
		
		f|format)
			echo 'yes-argumented'
		;;
		
		*)
			echo 'no'
		;;
		
	esac
}

_program_commandLine_processOptionWithoutArgument()
{
	:
}

_program_commandLine_processOptionWithArgument()
{
	case "$optionName" in
		
		o|output-path)
			core_validate_folderPathIsReadableAndSearchableAndWritableOrCanBeCreated $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			banias_outputPath="$optionValue"
		;;
		
		r|reports-path)
			core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			banias_reportsPath="$optionValue"
		;;
		
		f|format)
			banias_validate_format $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			banias_format="$optionValue"
		;;
		
	esac
}

_program_commandLine_handleNonOptions()
{
	core_variable_array_initialise banias_potentialReports
	core_variable_array_append banias_potentialReports "$@"
}

_program_commandLine_validate()
{
	if core_variable_isUnset banias_reportsPath; then
		banias_reportsPath="$banias_reportsPath_default"
	else
		core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_CONFIG 'configuration setting' 'banias_reportsPath' "$banias_reportsPath"
	fi

	if core_variable_isUnset banias_outputPath; then
		banias_outputPath="$banias_outputPath_default"
	else
		core_validate_folderPathIsReadableAndSearchableAndWritableOrCanBeCreated $core_commandLine_exitCode_CONFIG 'configuration setting' 'banias_outputPath' "$banias_outputPath"
	fi

	if core_variable_isUnset banias_format; then
		banias_format="$banias_format_default"
	else
		banias_validate_format $core_commandLine_exitCode_CONFIG 'configuration setting' 'banias_format' "$banias_format"
	fi
}

. "$_program_libPath"/shellfire/core/init.functions "$@"
