#!/usr/bin/env sh

# Oddly, makes the alt text use smart quotes but not the title of an image...
pandoc --smart --toc --to html5 -o html5.orig.html --template html5/default.html5 html5/html5.md
export PANDOC_LUA_BANIAS_DEBUG='false'
PANDOC_LUA_BANIAS_WRITER='html5' pandoc --smart --toc --to ./main.lua -o html5.html --template html5/default.html5 html5/html5.md
